version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db


  nodejs1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs1
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - DB_USER=admin
      - DB_PASS=admin
      - DB_HOST=mongo
      - DB_NAME=blog
    depends_on:
      - mongo

  nodejs2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs2
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - DB_USER=admin
      - DB_PASS=admin
      - DB_HOST=mongo
      - DB_NAME=blog
    depends_on:
      - mongo

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs1
      - nodejs2

volumes:
  mongo-data:
